apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    type: {{ .Values.deployment.label }}
  ports:
    - protocol: TCP
      port:  {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.container.port }}